### ISSUE TITLE
Included files don't take macro create in the source file in account

### ISSUE THREAD

**Issue by wyfo** [JhnW/devana#15]
Here is a minimal reproducible example:
```c
/* api.h */
#ifdef _MSC_VER
#define ALIGN(n) __declspec(align(n))
#else
#define ALIGN(n) __attribute__((aligned(n)))
#endif

#include "dependency.h"

/* dependency.h */
typedef struct ALIGN(8) my_type_t {
  int i;
} my_type_t;
```
Parsing code:
```python
module = SourceModule("my_api", "my_directory", ModuleFilter(["api.h"]))
print([str(c) for c in (*module.files,)[0].includes[0].source_file.content])
# print `['ClassInfo:ALIGN (<devana.syntax_abstraction.classinfo.ClassInfo object at 0x10321d520>)', 'GlobalVariable:my_type_t (<devana.syntax_abstraction.variable.GlobalVariable object at 0x10321d3d0>)']`
```

Looking at the code, included file are parsed in a in a different unit than the source file, so this behavior is explainable.
I don't know libclang enough to fix the issue by myself for now – I've started using it just one hour ago.

**Comment by wyfo** [comment]
I should have been more explicit about what I was expecting from devana, sorry.
If I put the content of `dependency.h` directly in `api.h`, it works fine and I obtain:
```
['ClassInfo:my_type_t (<devana.syntax_abstraction.classinfo.ClassInfo object at 0x104ebfad0>)', 'TypedefInfo:my_type_t (<devana.syntax_abstraction.typedefinfo.TypedefInfo object at 0x104ebea50>)']
```
My only issue is not about c-style structs, or compiler attributes, or code before preprocessing (I want in fact the preprocessed code), and I would be fine with the `ClassInfo`. The issue is that if `ALIGN` macro is declared in another file, the parsing does return random things when `ALIGN` is encountered, because devana doesn't put all the files in the same translation unit.

**Comment by JhnW** [comment]
Because you have to use include directives - as for normal C++ code. For different folders, you can configure include paths as for a normal compiler. You can always preview parse errors by using: https://jhnw.github.io/devana/api/devana.syntax_abstraction.organizers.html#devana.syntax_abstraction.organizers.sourcefile.SourceFile.diagnostics 

Files parsed by devana must be valid C/C++ files including using  include.
In fact, I add some a lot of magic to it - we come with our own libcxx headers which are the default std lib used for parsing, or I merge multiple translation units to concatenate the namespace into one structure but this is magic built at the level of libclang which is almost the same parse that the compiler uses (and just as nasty to use, but still incomparably better than what could once be obtained with gcc).
